name: flutter_app
description: Application with flutter.

version: 2.0.3+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  #Network
  dio: ^5.1.2
  connectivity_plus: ^4.0.1
  logger: ^1.3.0

  #Boilerplate
  get_it: ^7.7.0
  hive: ^2.2.3
  rxdart: ^0.27.7
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  url_strategy: ^0.2.0

  #Other
  flutter_svg: ^2.0.6
  device_info_plus: ^9.0.1
  intl: ^0.18.1
  gif_view: ^0.4.3
  lottie: ^3.1.0
  easy_image_viewer: ^1.5.0
  go_router: ^14.1.0

dev_dependencies:
  flutter_lints: ^2.0.1

#flutter_icons:
#  image_path: "assets/icon.png"
#  android: true
#  ios: true
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/png/
    - assets/images/jpg/
    - assets/images/svg/
    - assets/images/gif/
    - assets/images/lottie/
    - assets/fonts/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100

flutter_intl:
  enabled: true
